++++++++++          ; [0] = 10 — подготовим счётчик для цикла
; начало цикла
[
 >                  ; перешли к [1]
 +++++++            ; [1] += 7  → после цикла: 7*10 = 70
 >                  ; [2]
 ++++++++++         ; [2] += 10 → 10*10 = 100
 >                  ; [3]
 +++                ; [3] += 3  → 3*10 = 30
 >                  ; [4]
 +                  ; [4] += 1  → 1*10 = 10
 <<<<               ; назад к [0]
 -                  ; [0]-- → уменьшаем счётчик
]                   ; конец цикла (повторяется 10 раз)

; выводим строку (посимвольно)
>++~                ; [1] = 070+002 = 072 → 'H'
>+~                 ; [2] = 100+001 = 101 → 'e'
+++++++~            ; [2] =           108 → 'l'
~                   ; [2] =           108 → 'l'
+++~                ; [2] =           111 → 'o'
>++~                ; [3] = 030+002 = 032 → ' '
<<+++++++++++++++~  ; [1] = 072+015 = 087 → 'W'
>~                  ; [2] =           111 → 'o'
+++~                ; [2] =           114 → 'r'
------~             ; [2] =           108 → 'l'
--------~           ; [2] =           100 → 'd'
>+~                 ; [3] = 032+001 = 033 → '!'