Цикл формирования основных чисел
++++++++++
[
>+++++++
>++++++++++
>+++
>+
<<<<-
]
Вывод первого слова
>++~
>+~
+++++++~~
+++~
>++~
Вывод второго слова с повторным использованием ячеек
<<+++++++++++++++~
>~
+++~
------~
--------~
>+~
>~